{% set name = "polaris" %}
{% set version = "0.13.0" %}
{% set python_min = "3.10" %}
{% set python_max = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/polaris-lib/polaris_lib-{{ version }}.tar.gz
  sha256: e39d5a2e5ca7870755b50a3995f0892ffcec4df63e69ea3cafa45fe853acaf5b

build:
  entry_points:
    - polaris = polaris.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }},<={{ python_max }}
    - aiohttp
    - authlib
    - boto3 <1.36.0
    - datamol >=0.12.1
    - fastpdb
    - fsspec
    - httpx
    - numcodecs >=0.13.1,<0.16.0
    - numpy <3
    - pandas
    - pyarrow <18
    - pydantic >=2
    - pydantic-settings >=2
    - pyroaring
    - pyyaml
    - requests
    - rich >=13.9.4
    - scikit-learn
    - scipy
    - seaborn
    - tqdm
    - typer
    - typing-extensions >=4.12.0
    - zarr >=2,<3

test:
  requires:
    - python {{ python_min }}
  commands:
    - polaris --help
    - python -c "import polaris; assert polaris.__version__ == '{{ version }}'"

about:
  summary: Client for the Polaris Hub.
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/polaris-hub/polaris

extra:
  recipe-maintainers:
    - Andrewq11
    - cwognum
