{% set name = "polaris" %}
{% set version = "0.7.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/polaris-lib/polaris_lib-{{ version }}.tar.gz
  sha256: a3bfcfb7e9eb954250d9a34fada1f1f7232aa1dedb51b816280d9e640d7b6e64

build:
  entry_points:
    - polaris = polaris.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.10
    - tqdm
    - loguru
    - typer
    - pyyaml
    - pydantic >=2
    - pydantic-settings >=2
    - authlib
    - httpx
    - tenacity
    - filelock
    - numpy
    - pandas <2.2.0
    - scipy
    - scikit-learn
    - seaborn
    - datamol >=0.12.1
    - zarr
    - pyarrow
    - fsspec
    - yaspin

test:
  imports:
    - polaris
  commands:
    - pip check
    - polaris --help
  requires:
    - pip

about:
  summary: Client for the Polaris Hub.
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/polaris-hub/polaris

extra:
  recipe-maintainers:
    - cwognum
